version: "3.9"

services:
  downstream-api:
    build:
      context: ./downstream-api
    image: entra-id/downstream-api:local
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${DOWNSTREAM_API_AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${DOWNSTREAM_API_AZURE_CLIENT_SECRET}
      - AZURE_APP_ID_URL=${DOWNSTREAM_API_AZURE_APP_ID_URI}
    ports:
      - "8082:8080"

  middle-tier-api:
    build:
      context: ./middle-tier-api
    image: entra-id/middle-tier-api:local
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${MIDDLE_TIER_API_AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${MIDDLE_TIER_API_AZURE_CLIENT_SECRET}
      - AZURE_APP_ID_URL=${MIDDLE_TIER_API_AZURE_APP_ID_URI}
      - DOWNSTREAM_READ_SCOPE=${DOWNSTREAM_API_AZURE_APP_ID_URI}/Downstream.Read
      - DOWNSTREAM_WRITE_SCOPE=${DOWNSTREAM_API_AZURE_APP_ID_URI}/Downstream.Write
    ports:
      - "8081:8080"
    depends_on:
      - downstream-api

  web-app:
    build:
      context: ./web-app
    image: entra-id/web-app:local
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${WEB_APP_AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${WEB_APP_AZURE_CLIENT_SECRET}
      - AZURE_APP_ID_URL=${WEB_APP_AZURE_APP_ID_URI}
      - MIDDLE_TIER_READ_SCOPE=${MIDDLE_TIER_API_AZURE_APP_ID_URI}/MiddleTier.Read
      - MIDDLE_TIER_WRITE_SCOPE=${MIDDLE_TIER_API_AZURE_APP_ID_URI}/MiddleTier.Write
    ports:
      - "8080:8080"
    depends_on:
      - middle-tier-api
