spring:
  application:
    name: middle-tier-api
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        authorization-clients:
          downstream-api: # When authorization-grant-type is null, on behalf of flow is used by default
            authorization-grant-type: on_behalf_of
            scopes:
              - ${DOWNSTREAM_READ_SCOPE}
              - ${DOWNSTREAM_WRITE_SCOPE}
logging:
  level:
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    com.azure.spring.cloud.autoconfigure.aad: DEBUG