spring:
  application:
    name: middle-tier-api
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${MIDDLE_TIER_API_AZURE_CLIENT_ID}
          client-secret: ${MIDDLE_TIER_API_AZURE_CLIENT_SECRET}
        app-id-uri: ${MIDDLE_TIER_API_AZURE_APP_ID_URI}
        authorization-clients:
          downstream-api:
            authorization-grant-type: on_behalf_of
            scopes:
              - ${DOWNSTREAM_API_AZURE_APP_ID_URI}/Downstream.Read
              - ${DOWNSTREAM_API_AZURE_APP_ID_URI}/Downstream.Write
logging:
  level:
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    com.azure.spring.cloud.autoconfigure.aad: DEBUG