spring:
  application:
    name: web-app
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${WEB_APP_AZURE_CLIENT_ID}
          client-secret: ${WEB_APP_AZURE_CLIENT_SECRET}
        user-name-attribute: preferred_username
        app-id-uri: ${WEB_APP_AZURE_APP_ID_URI}
        authorization-clients:
          middle-tier-api:
            scopes:
              - ${MIDDLE_TIER_API_AZURE_APP_ID_URI}/MiddleTier.Read
              - ${MIDDLE_TIER_API_AZURE_APP_ID_URI}/MiddleTier.Write

logging:
  level:
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    com.azure.spring.cloud.autoconfigure.aad: DEBUG